version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=mypassword
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: studentcrud
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
